WITH YEAR_SCORE AS (
SELECT SUM(SCORE) SCORE, EMP_NO, RANK() OVER (ORDER BY SUM(SCORE) DESC) RANKING
FROM HR_GRADE
WHERE year = 2022
GROUP BY EMP_NO
)

SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM YEAR_SCORE
LEFT JOIN HR_EMPLOYEES
USING(EMP_NO)
WHERE RANKING = 1